version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geolocation_db
      IPSTACK_API_ACCESS_KEY: f91088e11ab0cef7179d7d02c63a63aa # TODO: use more secured approach instead

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geolocation_db

volumes:
  db_data: